- src: git+https://github.com/VoightCloud/GoldCent7Required.git
  name: required_software
  version: main
  scm: git
- src: git+https://github.com/VoightCloud/CentosSCAPScan.git
  name: scapscan
  version: main
  scm: git
#- src: git+https://github..com/M-A/register_agents.git
#  name: register_agents
#  version: main
#  scm: git
#- src: git+https://github.com/M-A/aide-update.git
#  name: aide_update
#  version: master
